---
- hosts: all
  become: true
  tasks:
    - name: install docker
      apt:
        name:
          - docker
        #update_cache: yes
    # module pour copier un fichier
    - name: file copy
      copy:
        src: /Desktop/FORMATION/Kubernetes/exercices/ex8-CORRECTION/TPDocker/correction-kubernetes/result
        dest: /Desktop/FORMATION/Ansible/ex2
    