---
- hosts: all
  become: true
  tasks:
    - name: install docker
      apt:
        name:
          - docker
        #update_cache: yes
    # module pour copier un fichier
    - name: file copy
      copy:
        src: docs/
        dest: /docs
    