---

- hosts: all 
  become: true 
  tasks:
  - name: Update the apt package index
    become: yes
    apt:
      name: "*"
      state: latest
      update_cache: yes
      force_apt_get: yes
    when: ansible_facts['os_family'] == "Debian"
  - name: Update the yum package index
    become: yes
    yum:
      name: "*"
      state: latest
      update_cache: yes
      force_apt_get: yes
    when: ansible_facts['os_family'] == "RedHat"


  - name: Install packages for apt add repository over HTTPS
    become: yes
    apt:
      name: "{{ packagesdep }}"
      force_apt_get: yes
      state: latest
      update_cache: yes
    vars:
      packagesdep:
      - git
      - apt-transport-https
      - ca-certificates
      - wget
      - software-properties-common
      - gnupg2
      - curl
    when: ansible_facts['os_family'] == "Debian"
  - name: Install packages for yum add repository over HTTPS
    become: yes
    yum:
      name: "{{ packagesdep }}"
      force_apt_get: yes
      state: latest
      update_cache: yes
    vars:
      packagesdep:
      - git
      - apt-transport-https
      - ca-certificates
      - wget
      - software-properties-common
      - gnupg2
      - curl
    when: ansible_facts['os_family'] == "RedHat"

  - name: Add Apt signing key from official docker repo
    apt_key:
      url: https://download.docker.com/linux/debian/gpg
      state: present
  - name: Add Apt signing key from official docker repo yum
    apt_key:
      url: https://download.docker.com/linux/centos/gpg
      state: present
  - name: add docker official repository for Debian Stretch
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/debian stretch stable
      state: present
  - name: add docker official repository for CentOS Stretch
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/centos stretch stable
      state: present
  - name: Index new repo into the cache
    become: yes
    apt:
      name: "*"
      state: latest
      update_cache: yes
      force_apt_get: yes
    when: ansible_facts['os_family'] == "Debian"
  - name: Index new repo into the cache yum
    become: yes
    yum:
      name: "*"
      state: latest
      update_cache: yes
      force_apt_get: yes
    when: ansible_facts['os_family'] == "RedHat"

  - name: actually install docker
    apt:
      name: "docker-ce"
      state: latest
    when: ansible_facts['os_family'] == "Debian"
  - name: actually install docker yum
    yum:
      name: "docker-ce"
      state: latest
    when: ansible_facts['os_family'] == "RedHat"
  
  - name: Run and enable docker
    service:
     name: docker
     state: started
     enabled: true
  
  